language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - FLASK_VERSION=1.0
  - FLASK_VERSION=1.1
install:
  - pip install -q Flask==$FLASK_VERSION
  - pip install -q -r requirements-dev.txt
  - python setup.py install
script:
  - pylama -o pytest.ini
  - python -Wall runtests.py